### ISSUE TITLE
Created a helm chart

### ISSUE THREAD

**Issue by softlion** [wwadge/awair-bridge#1]
Hey !
Ty for the tool.
I create a helm chart to run it on any kubernetes cluster quickly:

https://github.com/softlion/awair-bridge

**Comment by wwadge** [comment]
Thanks. Mind opening a PR?

**Comment by wwadge** [comment]
Also it's simplified now, no need for disk access and takes a username/password instead of "initialToken"

**Comment by softlion** [comment]
Updated.

would be nice to include https://github.com/carcabot/docker-tuxlervpn-server

which would use https://www.tuxlervpn.com/

Because this cloudflare config is .................. annoying. blocking all vps IPs.

You can test your IP there:
https://www.ip2location.com/demo/90.150.110.220

If usage type is not ISP (ie: DCH) cloudflare blocks you.

**Comment by wwadge** [comment]
Interesting... and should already work now by setting env var to JAVA_TOOL_OPTIONS="-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=12345"

**Comment by wwadge** [comment]
Probably best if your helm chart adds the vpn thing as a sidecar container so all traffic gets routed easily (via JAVA_TOOL_OPTIONS flag)
