### ISSUE TITLE
pwLogin issue on Ubuntu

### ISSUE THREAD

**Issue by killtheplanet** [wwadge/awair-bridge#3]
Hi,

First off - thanks for this - we need headless!

The README.md says to use pwlogin.sh whilst I assume it should read pwLogin.sh

Verified pup and jq is in my path - however once specifying the credentials it appears that the loginForm variable is not being filled in, snippit running with bash -x:

```

++ curl -sSL --get --cookie /tmp/cookie.jar.Fr0F --cookie-jar /tmp/cookie.jar.Fr0F --ciphers ECDHE-RSA-AES128-GCM-SHA256 -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) awair-uploader/0.0.1 Chrome/96.0.4664.110 Electron/16.0.7 Safari/537.36' --data-urlencode client_id=external-login --data-urlencode redirect_uri=http://localhost:33333/keycloak-redirect --data-urlencode 'scope=openid offline_access' --data-urlencode response_type=code --data-urlencode code_challenge=FnVdSgvbpqc_ImqAFBw1n52EIF1s2ZUULdgRGRSDZHg --data-urlencode code_challenge_method=S256 https://login.planetwatch.io/auth/realms/Planetwatch/protocol/openid-connect/auth
+ loginForm=
+ loginForm=
++ curl -sS --cookie /tmp/cookie.jar.Fr0F --cookie-jar /tmp/cookie.jar.Fr0F --ciphers ECDHE-RSA-AES128-GCM-SHA256 -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) awair-uploader/0.0.1 Chrome/96.0.4664.110 Electron/16.0.7 Safari/537.36' --data-urlencode username=myuser@name.com--data-urlencode password=mypassword --write-out '%{redirect_url}' ''
curl: (3) URL using bad/illegal format or missing URL
+ codeUrl=
+ code=
```

The output of the first curl to https://login.planetwatch.io/auth/realms/Planetwatch/protocol/openid-connect/auth says:

`error code: 1020
`

Pointers welcome!

**Comment by wwadge** [comment]
You're a victim of cloudflare, it's blocking your IP range, probably because you're on a cloud platform

**Comment by wwadge** [comment]
(also I'm porting this script to code so that this script becomes redundant too)

**Comment by killtheplanet** [comment]
> You're a victim of cloudflare, it's blocking your IP range, probably because you're on a cloud platform

Hmm - have tried from 3 residential IP addresses now with no go, I'll login a bit to explorer trying to catch a token maybe...

Thanks!

**Comment by wwadge** [comment]
Please try pulling image again and check out the README.md, it will only need a awair token + pw.username/password now
