### ISSUE TITLE
not working on pi zero

### ISSUE THREAD

**Issue by pixelcatcher** [wwadge/awair-bridge#8]
docker: no matching manifest for linux/arm/v6 in the manifest list entries.

**Comment by wwadge** [comment]
I haven't been able to find a docker base image containing Java 17 for Arm-v6, if you find one let me know and I'll create a build for it.

Alternatively, run it manually outside of docker (provided you can find Java for armv6, in which case we can create a new base image)

**Comment by wwadge** [comment]
Project no longer needed
